import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Head from "next/head";
import 'tailwindcss/tailwind.css';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Recursos basicos do nextjs",
  description: "Generated by create next app"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <Header />
        {children}</body>
    </html>
  );
}
